// <auto-generated />
using System;
using CryptoTracker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoTracker.Migrations
{
    [DbContext(typeof(CryptoTrackerDbContext))]
    [Migration("20260130220034_AddAssetLotTracking")]
    partial class AddAssetLotTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CryptoTracker.Entities.AssetLot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AcquisitionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("AcquisitionPriceEur")
                        .HasColumnType("decimal(27, 12)");

                    b.Property<int>("AcquisitionType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrentWalletId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OriginalQuantity")
                        .HasColumnType("decimal(27, 12)");

                    b.Property<int?>("ParentLotId")
                        .HasColumnType("int");

                    b.Property<decimal>("RemainingQuantity")
                        .HasColumnType("decimal(27, 12)");

                    b.Property<int?>("SourceTradeId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceTransactionId")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TotalAcquisitionCostEur")
                        .HasColumnType("decimal(27, 12)");

                    b.HasKey("Id");

                    b.HasIndex("AcquisitionDate");

                    b.HasIndex("ParentLotId");

                    b.HasIndex("SourceTradeId");

                    b.HasIndex("SourceTransactionId");

                    b.HasIndex("CurrentWalletId", "Symbol");

                    b.ToTable("AssetLots");
                });

            modelBuilder.Entity("CryptoTracker.Entities.CryptoTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(27, 12)");

                    b.Property<decimal>("ForeignFee")
                        .HasColumnType("decimal(27, 12)");

                    b.Property<string>("ForeignFeeSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LotAssignmentConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("OppositeSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OppositeTradeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(27, 12)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(27, 12)");

                    b.Property<string>("Referenz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResultingLotId")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TradeType")
                        .HasColumnType("int");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OppositeTradeId")
                        .IsUnique()
                        .HasFilter("[OppositeTradeId] IS NOT NULL");

                    b.HasIndex("ResultingLotId");

                    b.HasIndex("WalletId");

                    b.ToTable("CryptoTrades");
                });

            modelBuilder.Entity("CryptoTracker.Entities.CryptoTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(27, 12)");

                    b.Property<bool>("LotAssignmentConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Network")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OppositeTransactionId")
                        .HasColumnType("int");

                    b.Property<int?>("OppositeWalletId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(27, 12)");

                    b.Property<int?>("ResultingLotId")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OppositeTransactionId")
                        .IsUnique()
                        .HasFilter("[OppositeTransactionId] IS NOT NULL");

                    b.HasIndex("OppositeWalletId");

                    b.HasIndex("ResultingLotId");

                    b.HasIndex("WalletId");

                    b.ToTable("CryptoTransactions");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.BinanceDepositEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Coin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TXID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TransactionFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("BinanceDeposits");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.BinanceTradeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Executed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pair")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("BinanceTrades");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.BinanceWithdrawalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Coin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TXID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TransactionFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("BinanceWithdrawals");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.BitcoinDeTransactionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CryptoNachGebuehr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CryptoVorGebuehr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("Datum")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EinheitKurs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EinheitMengeNachGebuehr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EinheitMengeVorGebuehr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kommentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Kontostand")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Kurs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MengeNachGebuehr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MengeVorGebuehr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Referenz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Waehrung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.Property<decimal>("ZuAbgang")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("BitcoinDeTransactions");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.BitpandaTransactionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AmountAsset")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AmountFiat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AssetMarketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AssetMarketPriceCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FeeAsset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fiat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InOut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Spread")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SpreadCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TaxFiat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("BitpandaTransactions");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.LedgerTransactionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Coin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Datum")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Kommentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TransactionFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("LedgerTransactions");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.MetamaskTradeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Executed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pair")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tradingplatform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("MetamaskTrades");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.MetamaskTransactionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Coin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Datum")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Kommentar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TransactionFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("MetamaskTransactions");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.OkxDepositEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Coin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TXID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TransactionFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("OkxDeposits");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.OkxTradeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Executed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Pair")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("OkxTrades");
                });

            modelBuilder.Entity("CryptoTracker.Entities.LotMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsTaxFree")
                        .HasColumnType("bit");

                    b.Property<int>("LotId")
                        .HasColumnType("int");

                    b.Property<int>("MovementType")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(27, 12)");

                    b.Property<decimal?>("RealizedGainEur")
                        .HasColumnType("decimal(27, 12)");

                    b.Property<int?>("ResultingLotId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SalePriceEur")
                        .HasColumnType("decimal(27, 12)");

                    b.Property<int?>("TaxFreeReason")
                        .HasColumnType("int");

                    b.Property<int?>("TradeId")
                        .HasColumnType("int");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DateTime");

                    b.HasIndex("LotId");

                    b.HasIndex("ResultingLotId");

                    b.HasIndex("TradeId");

                    b.HasIndex("TransactionId");

                    b.ToTable("LotMovements");
                });

            modelBuilder.Entity("CryptoTracker.Entities.ManualCoinPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("PriceEur")
                        .HasColumnType("decimal(27, 12)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Date")
                        .IsUnique();

                    b.ToTable("ManualCoinPrices");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("CryptoTracker.Entities.AssetLot", b =>
                {
                    b.HasOne("CryptoTracker.Entities.Wallet", "CurrentWallet")
                        .WithMany()
                        .HasForeignKey("CurrentWalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CryptoTracker.Entities.AssetLot", "ParentLot")
                        .WithMany("ChildLots")
                        .HasForeignKey("ParentLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CryptoTracker.Entities.CryptoTrade", "SourceTrade")
                        .WithMany()
                        .HasForeignKey("SourceTradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CryptoTracker.Entities.CryptoTransaction", "SourceTransaction")
                        .WithMany()
                        .HasForeignKey("SourceTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentWallet");

                    b.Navigation("ParentLot");

                    b.Navigation("SourceTrade");

                    b.Navigation("SourceTransaction");
                });

            modelBuilder.Entity("CryptoTracker.Entities.CryptoTrade", b =>
                {
                    b.HasOne("CryptoTracker.Entities.CryptoTrade", "OppositeTrade")
                        .WithOne()
                        .HasForeignKey("CryptoTracker.Entities.CryptoTrade", "OppositeTradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CryptoTracker.Entities.AssetLot", "ResultingLot")
                        .WithMany()
                        .HasForeignKey("ResultingLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CryptoTracker.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OppositeTrade");

                    b.Navigation("ResultingLot");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoTracker.Entities.CryptoTransaction", b =>
                {
                    b.HasOne("CryptoTracker.Entities.CryptoTransaction", "OppositeTransaction")
                        .WithOne()
                        .HasForeignKey("CryptoTracker.Entities.CryptoTransaction", "OppositeTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CryptoTracker.Entities.Wallet", "OppositeWallet")
                        .WithMany()
                        .HasForeignKey("OppositeWalletId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CryptoTracker.Entities.AssetLot", "ResultingLot")
                        .WithMany()
                        .HasForeignKey("ResultingLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CryptoTracker.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OppositeTransaction");

                    b.Navigation("OppositeWallet");

                    b.Navigation("ResultingLot");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.BinanceDepositEntity", b =>
                {
                    b.HasOne("CryptoTracker.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.BinanceTradeEntity", b =>
                {
                    b.HasOne("CryptoTracker.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.BinanceWithdrawalEntity", b =>
                {
                    b.HasOne("CryptoTracker.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.BitcoinDeTransactionEntity", b =>
                {
                    b.HasOne("CryptoTracker.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.BitpandaTransactionEntity", b =>
                {
                    b.HasOne("CryptoTracker.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.LedgerTransactionEntity", b =>
                {
                    b.HasOne("CryptoTracker.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.MetamaskTradeEntity", b =>
                {
                    b.HasOne("CryptoTracker.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.MetamaskTransactionEntity", b =>
                {
                    b.HasOne("CryptoTracker.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.OkxDepositEntity", b =>
                {
                    b.HasOne("CryptoTracker.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoTracker.Entities.Import.OkxTradeEntity", b =>
                {
                    b.HasOne("CryptoTracker.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoTracker.Entities.LotMovement", b =>
                {
                    b.HasOne("CryptoTracker.Entities.AssetLot", "Lot")
                        .WithMany("Movements")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoTracker.Entities.AssetLot", "ResultingLot")
                        .WithMany()
                        .HasForeignKey("ResultingLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CryptoTracker.Entities.CryptoTrade", "Trade")
                        .WithMany("LotMovements")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CryptoTracker.Entities.CryptoTransaction", "Transaction")
                        .WithMany("LotMovements")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lot");

                    b.Navigation("ResultingLot");

                    b.Navigation("Trade");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("CryptoTracker.Entities.AssetLot", b =>
                {
                    b.Navigation("ChildLots");

                    b.Navigation("Movements");
                });

            modelBuilder.Entity("CryptoTracker.Entities.CryptoTrade", b =>
                {
                    b.Navigation("LotMovements");
                });

            modelBuilder.Entity("CryptoTracker.Entities.CryptoTransaction", b =>
                {
                    b.Navigation("LotMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
