namespace CryptoTracker.Shared;

public record TransactionRowDTO(FlowType FlowType,
                                FlowDirection FlowDirection,
                                DateTimeOffset DateTime,
                                int FlowId,
                                string Symbol,
                                decimal Amount,
                                decimal EuroValue,
                                decimal RateEur,
                                decimal Fee,
                                string? SourceWallet,
                                string? TargetWallet,
                                string? Slug,
                                string? Comment,
                                bool HasOpposite,
                                string? TargetSymbol,
                                decimal? TargetAmount,
                                string? TargetSlug,
                                Guid RowKey);
