name: Cryptotracker Azure bicep deploy

permissions:
    id-token: write
    contents: read

on:
  workflow_dispatch:

jobs:
  bicep-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: OIDC Login to Azure Public Cloud with AzPowershell
      uses: azure/login@v1
      with:
        client-id: ${{ vars.AZURE_DEPLOYMENT_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: deploy
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP_NAME }}
        scope: resourcegroup
        template: ./infra/main.bicep
        parameters: ./infra/main.parameters.json azureDbConnectionString="${{ vars.AZURE_DB_CONNECTION_STRING }}"
        failOnStdErr: false
        
