name: Main Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --configuration Release \
          --logger "trx;LogFileName=test_results.trx" \
          --results-directory TestResults \
          --verbosity normal

      - name: Summarize test results
        if: always()
        run: |
          FAILED=$(grep -o 'outcome="Failed"' TestResults/test_results.trx | wc -l || true)
          PASSED=$(grep -o 'outcome="Passed"' TestResults/test_results.trx | wc -l || true)
          TOTAL=$((FAILED+PASSED))
          echo "### Unit Test Results" >> $GITHUB_STEP_SUMMARY
          echo "Total: $TOTAL" >> $GITHUB_STEP_SUMMARY
          echo "Passed: $PASSED" >> $GITHUB_STEP_SUMMARY
          echo "Failed: $FAILED" >> $GITHUB_STEP_SUMMARY

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TestResults/test_results.trx
